# Generated by Django 3.2.4 on 2024-02-07 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('mobile_number_verified', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=False)),
                ('avatar', models.ImageField(default='/api/account/avatar/defaultPic.png', upload_to='account/avatar/')),
                ('bio', models.TextField(default='write something about you...', max_length=420)),
                ('is_ingame', models.BooleanField(default=False)),
                ('win', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('two_fa', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=64, null=True)),
                ('opt_expiration', models.DateTimeField(blank=True, null=True)),
                ('totp_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('friend', models.ManyToManyField(blank=True, related_name='_account_userprofile_friend_+', to='account.UserProfile')),
                ('games_id', models.ManyToManyField(blank=True, to='game.Game')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
