# Generated by Django 3.2.4 on 2024-02-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/api/account/avatar/defaultPic.png', upload_to='avatar/'),
        ),
    ]
