# Generated by Django 3.2.4 on 2024-02-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/api/account/avatar/defaultPic.png', upload_to='account/avatar/'),
        ),
    ]
