# Generated by Django 4.2 on 2024-01-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_game_player_one_remove_game_player_two_and_more'),
        ('account', '0003_myuser_lose_myuser_win_alter_myuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='games_id',
            field=models.ManyToManyField(blank=True, to='game.game'),
        ),
    ]
