# Generated by Django 4.2 on 2024-01-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
