# Generated by Django 4.2 on 2024-01-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_player_one_game_player_two_game_winner'),
        ('account', '0014_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='games_id',
            field=models.ManyToManyField(blank=True, to='game.game'),
        ),
    ]
