# Generated by Django 4.2 on 2024-01-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_userprofile_games_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
