# Generated by Django 4.2 on 2024-01-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
