# Generated by Django 4.2 on 2024-01-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_userprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
