# Generated by Django 4.2 on 2024-01-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_userprofile_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_ingame',
            field=models.BooleanField(default=False),
        ),
    ]
