# Generated by Django 4.2 on 2024-01-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/api/account/profile/avatar/defaultPic.png', upload_to='avatar/'),
        ),
    ]
