# Generated by Django 4.2 on 2024-01-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_alter_userprofile_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
