# Generated by Django 3.2.4 on 2024-01-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('account', '0037_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chats',
            field=models.ManyToManyField(blank=True, to='chat.Chat'),
        ),
    ]
