# Generated by Django 3.2.4 on 2024-01-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_userprofile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='_account_userprofile_friend_+', to='account.UserProfile'),
        ),
    ]
