# Generated by Django 4.2 on 2024-01-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_userprofile_bio'),
        ('account', '0042_auto_20240130_1342'),
    ]

    operations = [
    ]
