# Generated by Django 3.2.4 on 2024-01-31 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='discussion',
        ),
        migrations.AddField(
            model_name='chat',
            name='discussion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
    ]
