# Generated by Django 3.2.4 on 2024-01-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_auto_20240130_1342'),
        ('friend_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_management',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friend_management',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='friend_management',
            name='friend1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to='account.userprofile'),
        ),
        migrations.AddField(
            model_name='friend_management',
            name='friend2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='account.userprofile'),
        ),
        migrations.AddField(
            model_name='friend_management',
            name='requester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='account.userprofile'),
        ),
    ]
