# Generated by Django 4.2 on 2024-01-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_final_score_alter_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_one',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_two',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
